openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/v1/game/score:
    get:
      tags:
      - game-score-controller
      operationId: getScore
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ScoreDto"
components:
  schemas:
    ScoreDto:
      type: object
      properties:
        A:
          type: string
        B:
          type: string
